### ISSUE TITLE
提示：panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by yuntao1223** [a1667834841/goFastForVideo#4]
大佬用用户名登陆的提示报错：
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
goFastForVideo/query.GetUserIdAndPlatId({0xc0003b03c0?, 0x172e288?}, {0xc0003b03d8?, 0x1?}, {0xc00000ff00?, 0x8?}, {{0x1697738, 0x8}, {0x0, 0x0}, ...})
        D:/project/vscode/goFastForVideo/query/queryForhtml.go:162 +0x17b
goFastForVideo/query.ReadDetailCourses.func1.1(0xc000006858?, 0xc00007d878?)
        D:/project/vscode/goFastForVideo/query/queryForhtml.go:109 +0x326
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0003ea6f0, 0xc00005f978)
        D:/installSoftWare/Go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.0/iteration.go:10 +0x46
goFastForVideo/query.ReadDetailCourses.func1(0xc000428048?, 0xc0003ea600)
        D:/project/vscode/goFastForVideo/query/queryForhtml.go:101 +0x1d3
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0003ea5d0, 0xc00005fae0)
        D:/installSoftWare/Go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.0/iteration.go:10 +0x46
goFastForVideo/query.ReadDetailCourses({0xc0003b03c0, 0x7}, {0xc0003b03d8, 0x6}, {{0xc000017db0, 0x4f}, {0xc00000fe80, 0x3b}, {0xc00000fec0, 0x3d}})
        D:/project/vscode/goFastForVideo/query/queryForhtml.go:88 +0xde
goFastForVideo/query.ReadCourses.func1(0xc000006820?, 0xc0003ea4b0?)
        D:/project/vscode/goFastForVideo/query/queryForhtml.go:71 +0x33d
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0003ea480, 0xc00005fd80)
        D:/installSoftWare/Go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.0/iteration.go:10 +0x46
goFastForVideo/query.ReadCourses({0xc0003b03c0, 0x7}, {0xc0003b03d8, 0x6}, 0xc00000cde0?)
        D:/project/vscode/goFastForVideo/query/queryForhtml.go:61 +0x168
main.main()
        D:/project/vscode/goFastForVideo/main.go:21 +0x1c5
![image](https://user-images.githubusercontent.com/35868506/179967168-2c726dbd-936c-4ce7-9aa2-d1fed389e09a.png)

**Comment by a1667834841** [comment]
介意提供下账号密码吗 我这边测试下
可以发我邮箱 1667834841@qq.com

**Comment by a1667834841** [comment]
你可以再更新下 应该修复好了
